name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Unzip launcher
        run: |
          ZIP=$(ls *.zip | head -n 1)
          echo "Descompactando $ZIP"
          unzip -o "$ZIP"
          # Se o zip criou uma pasta, puxa tudo pra raiz
          if [! -f "./gradlew" ]; then
            for d in */; do
              if [ -f "$d/gradlew" ]; then
                cp -r $d/*.
                break
              fi
            done
          fi
          ls -la
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Grant execute
        run: chmod +x gradlew
      - name: Build APK
        run:./gradlew assembleDebug
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: TheLastDayZ-APK
          path: app/build/outputs/apk/debug/app-debug.apk
